import { useEffect, useMemo, useState } from "react";
import { useMeterSocket } from "./useMeterSocket.ts";
import { MeterTable } from "./MeterTable.tsx";
import { Header } from "./Header.tsx";
import { Footer } from "./Footer.tsx";
import { SettingsPanel } from "./SettingsPanel.tsx";
import { DrillIn } from "./DrillIn.tsx";
import { ActivityLog } from "./ActivityLog.tsx";
import { SessionStrip } from "./SessionStrip.tsx";
import { accentOklch, useSettings } from "./useSettings.ts";
import type { Mode, PlayerSnapshot } from "./types.ts";

function useStored(key: string, initial: string): [string, (v: string) => void] {
	const [v, setV] = useState<string>(() => {
		try {
			return localStorage.getItem(key) ?? initial;
		} catch {
			return initial;
		}
	});
	useEffect(() => {
		try {
			localStorage.setItem(key, v);
		} catch {
			/* private mode etc. */
		}
	}, [key, v]);
	return [v, setV];
}

const DEFAULT_VIEW_URL = "wss://albion-meter.goldpipe.workers.dev/view";

// readPairFromURL returns ?pair=<token> from the current URL and strips the
// query param so a refresh / bookmark doesn't keep showing it.
function readPairFromURL(): string | null {
	try {
		const params = new URLSearchParams(window.location.search);
		const pair = params.get("pair");
		if (!pair) return null;
		// Strip the param so the URL stays clean. replaceState avoids a
		// navigation but updates the address bar + bookmarks behaviour.
		params.delete("pair");
		const qs = params.toString();
		const newUrl = window.location.pathname + (qs ? "?" + qs : "") + window.location.hash;
		window.history.replaceState({}, "", newUrl);
		return pair.trim();
	} catch {
		return null;
	}
}

export default function App(): React.ReactElement {
	const [url, setUrl] = useStored("skirmish:url", "");
	const [token, setToken] = useStored("skirmish:token", "");
	const [modeStored, setModeStored] = useStored("skirmish:mode", "damage");

	// Auto-pair from a magic link generated by the local agent on first run.
	// /?pair=<32-hex-token> wires the meter to that agent without anyone
	// typing a token. Runs exactly once on mount; the URL is cleaned even
	// when the token in the link matches what's already stored.
	useEffect(() => {
		const fromURL = readPairFromURL();
		if (!fromURL) return;
		if (!url) setUrl(DEFAULT_VIEW_URL);
		if (fromURL !== token) setToken(fromURL);
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);
	const mode = (["damage", "heal", "taken", "mechanics"].includes(modeStored)
		? modeStored
		: "damage") as Mode;

	const { settings, update, reset } = useSettings();
	const [showSettings, setShowSettings] = useState(false);
	const [drillGuid, setDrillGuid] = useState<string | null>(null);

	const configured = url.trim() !== "" && token.trim() !== "";
	const { state, snapshot, lastMessageAt, error, sendCommand } = useMeterSocket({
		url: url.trim(),
		token: token.trim(),
		enabled: configured,
	});

	const onNewSession = (): void => {
		if (!confirm("Reset the session? This wipes combat stats, fight count, fame/silver/respec totals, and the activity log on the agent.")) {
			return;
		}
		const ok = sendCommand("resetSession");
		if (!ok) {
			alert("Couldn't reach the agent — connection isn't open. Make sure agent.exe is running.");
		}
	};

	// Apply the chosen accent color as CSS variables so every component
	// re-tints without a re-render. Drives --sk-local + --sk-local-tint
	// across the whole tree.
	useEffect(() => {
		const { fg, tint } = accentOklch(settings.accent);
		document.documentElement.style.setProperty("--sk-local", fg);
		document.documentElement.style.setProperty("--sk-local-tint", tint);
	}, [settings.accent]);

	const stale = useMemo(() => {
		if (!lastMessageAt) return false;
		return Date.now() - lastMessageAt > 5000;
	}, [lastMessageAt, state, snapshot]);

	if (!configured) {
		return <SetupScreen url={url} token={token} setUrl={setUrl} setToken={setToken} />;
	}

	const triple = settings.paneMode === "triple";

	return (
		<div className="min-h-dvh flex flex-col" style={{ background: "var(--sk-bg-0)", color: "var(--sk-fg-0)" }}>
			<Header
				state={state}
				stale={stale}
				snapshot={snapshot}
				mode={mode}
				setMode={(m) => setModeStored(m)}
				onSettings={() => setShowSettings(true)}
				onReset={() => {
					if (confirm("Disconnect and clear settings?")) {
						setUrl("");
						setToken("");
					}
				}}
				onToggleLog={() => update("showActivityLog", !settings.showActivityLog)}
				showLog={settings.showActivityLog}
				hideTabs={triple}
			/>
			<SessionStrip snapshot={snapshot} onReset={onNewSession} />
			<main className="flex-1 overflow-hidden flex flex-col">
				<div className="flex-1 overflow-hidden">
					{triple ? (
						<TriplePane
							snapshot={snapshot}
							settings={settings}
							onDrillIn={(p: PlayerSnapshot) => setDrillGuid(p.userGuid)}
						/>
					) : (
						<div className="h-full overflow-auto">
							<MeterTable
								snapshot={snapshot}
								mode={mode}
								settings={settings}
								onDrillIn={(p: PlayerSnapshot) => setDrillGuid(p.userGuid)}
							/>
						</div>
					)}
				</div>
				{error && (
					<div
						className="px-4 py-2 sk-upper"
						style={{ color: "var(--sk-err)", borderTop: "1px solid var(--sk-line)" }}
					>
						connection: {error}
					</div>
				)}
				{settings.showActivityLog && <ActivityLog snapshot={snapshot} />}
			</main>
			<Footer snapshot={snapshot} lastMessageAt={lastMessageAt} />
			{showSettings && (
				<SettingsPanel
					settings={settings}
					update={update}
					reset={reset}
					onClose={() => setShowSettings(false)}
				/>
			)}
			{drillGuid && snapshot && (() => {
				const p = snapshot.players.find((p) => p.userGuid === drillGuid);
				return p ? <DrillIn player={p} onClose={() => setDrillGuid(null)} /> : null;
			})()}
		</div>
	);
}

// TriplePane renders three meter tables side-by-side, one each for damage,
// healing, and taken damage. Each pane has its own caption row showing
// what metric is locked in.
function TriplePane({
	snapshot,
	settings,
	onDrillIn,
}: {
	snapshot: ReturnType<typeof useMeterSocket>["snapshot"];
	settings: ReturnType<typeof useSettings>["settings"];
	onDrillIn: (p: PlayerSnapshot) => void;
}): React.ReactElement {
	const panes: Array<{ mode: Mode; label: string; tone: string }> = [
		{ mode: "damage", label: "Damage",  tone: "var(--sk-damage)" },
		{ mode: "heal",   label: "Healing", tone: "var(--sk-heal)" },
		{ mode: "taken",  label: "Taken",   tone: "var(--sk-taken)" },
	];
	return (
		<div className="grid h-full" style={{ gridTemplateColumns: "1fr 1fr 1fr" }}>
			{panes.map((p, i) => (
				<div
					key={p.mode}
					className="flex flex-col overflow-hidden"
					style={{ borderRight: i < 2 ? "1px solid var(--sk-line)" : "none" }}
				>
					<div
						className="sk-upper flex items-center"
						style={{
							padding: "8px 14px",
							borderBottom: "1px solid var(--sk-line)",
							color: p.tone,
							fontWeight: 600,
							background: "var(--sk-bg-1)",
							gap: 8,
						}}
					>
						<span
							style={{
								width: 6,
								height: 6,
								borderRadius: 99,
								background: p.tone,
							}}
						/>
						{p.label}
					</div>
					<div className="flex-1 overflow-auto">
						<MeterTable
							snapshot={snapshot}
							mode={p.mode}
							settings={settings}
							onDrillIn={onDrillIn}
						/>
					</div>
				</div>
			))}
		</div>
	);
}

interface SetupScreenProps {
	url: string;
	token: string;
	setUrl: (v: string) => void;
	setToken: (v: string) => void;
}

function SetupScreen({ url, token, setUrl, setToken }: SetupScreenProps): React.ReactElement {
	const [localUrl, setLocalUrl] = useState(url || DEFAULT_VIEW_URL);
	const [localToken, setLocalToken] = useState(token);

	return (
		<div className="min-h-dvh flex items-center justify-center p-4" style={{ background: "var(--sk-bg-0)" }}>
			<form
				className="w-full max-w-sm"
				style={{
					background: "var(--sk-bg-1)",
					border: "1px solid var(--sk-line)",
					borderRadius: 8,
					padding: 22,
				}}
				onSubmit={(e) => {
					e.preventDefault();
					setUrl(localUrl.trim());
					setToken(localToken.trim());
				}}
			>
				<div className="flex items-center mb-2.5" style={{ gap: 7 }}>
					<svg width="18" height="18" viewBox="0 0 18 18" style={{ display: "block" }}>
						<rect x="1.5" y="3"  width="11" height="2" fill="var(--sk-damage)" />
						<rect x="1.5" y="8"  width="15" height="2" fill="var(--sk-fg-0)" />
						<rect x="1.5" y="13" width="6"  height="2" fill="var(--sk-local)" />
					</svg>
					<span
						style={{
							fontFamily: "var(--sk-font-mono)",
							fontSize: 12.5,
							fontWeight: 600,
							letterSpacing: "0.18em",
							color: "var(--sk-fg-0)",
							textTransform: "uppercase",
						}}
					>
						Skirmish
					</span>
				</div>

				<h1 style={{ fontSize: 17, fontWeight: 500, marginBottom: 6, color: "var(--sk-fg-0)" }}>
					Manual pairing
				</h1>
				<p style={{ fontSize: 12, color: "var(--sk-fg-2)", marginBottom: 18, lineHeight: 1.5 }}>
					You usually don't need this screen — the agent opens this page for
					you on first run and auto-pairs. Use this only if you closed that
					tab, or you want to point a second browser at the same agent. Copy
					the <span className="sk-mono" style={{ color: "var(--sk-fg-0)" }}>pushToken</span> value from
					your <span className="sk-mono" style={{ color: "var(--sk-fg-0)" }}>agent/agent.json</span>.
				</p>

				<label className="block">
					<div className="flex items-baseline justify-between" style={{ marginBottom: 6 }}>
						<span className="sk-upper" style={{ color: "var(--sk-fg-3)" }}>Pairing token</span>
					</div>
					<input
						type="text"
						value={localToken}
						onChange={(e) => setLocalToken(e.target.value)}
						placeholder="paste pushToken from agent.json"
						className="sk-mono"
						style={{
							width: "100%",
							background: "var(--sk-bg-0)",
							border: "1px solid var(--sk-line)",
							borderRadius: 4,
							padding: "8px 10px",
							fontSize: 12,
							color: "var(--sk-fg-0)",
							outline: "none",
						}}
					/>
				</label>

				<details style={{ marginTop: 14 }}>
					<summary
						className="sk-upper"
						style={{ color: "var(--sk-fg-3)", cursor: "pointer", listStyle: "none" }}
					>
						Advanced — Worker URL
					</summary>
					<input
						type="text"
						value={localUrl}
						onChange={(e) => setLocalUrl(e.target.value)}
						style={{
							marginTop: 8,
							width: "100%",
							background: "var(--sk-bg-0)",
							border: "1px solid var(--sk-line)",
							borderRadius: 4,
							padding: "6px 9px",
							fontSize: 11,
							color: "var(--sk-fg-1)",
							outline: "none",
							fontFamily: "var(--sk-font-mono)",
						}}
					/>
				</details>

				<button
					type="submit"
					disabled={!localToken.trim()}
					style={{
						marginTop: 20,
						width: "100%",
						appearance: "none",
						background: "var(--sk-local)",
						color: "var(--sk-bg-0)",
						border: 0,
						borderRadius: 4,
						padding: "9px 12px",
						fontSize: 12.5,
						fontWeight: 600,
						cursor: localToken.trim() ? "pointer" : "not-allowed",
						opacity: localToken.trim() ? 1 : 0.5,
					}}
				>
					Connect
				</button>

				<p style={{ marginTop: 14, fontSize: 11, color: "var(--sk-fg-3)", lineHeight: 1.5 }}>
					Anyone with this token sees the same meter room. Keep it private
					unless you want to share.
				</p>
			</form>
		</div>
	);
}
