package gamecodes

// Code generated from src/StatisticsAnalysisTool/Network/EventCodes.cs. DO NOT EDIT.

type Event int

const (
	EventUnused Event = iota
	EventLeave
	EventJoinFinished
	EventMove
	EventTeleport
	EventChangeEquipment
	EventHealthUpdate
	EventHealthUpdates
	EventEnergyUpdate
	EventDamageShieldUpdate
	EventCraftingFocusUpdate
	EventActiveSpellEffectsUpdate
	EventResetCooldowns
	EventAttack
	EventCastStart
	EventChannelingUpdate
	EventCastCancel
	EventCastTimeUpdate
	EventCastFinished
	EventCastSpell
	EventCastSpells
	EventCastHit
	EventCastHits
	EventStoredTargetsUpdate
	EventChannelingEnded
	EventAttackBuilding
	EventInventoryPutItem
	EventInventoryDeleteItem
	EventInventoryState
	EventNewCharacter
	EventNewEquipmentItem
	EventNewSiegeBannerItem
	EventNewSimpleItem
	EventNewFurnitureItem
	EventNewKillTrophyItem
	EventNewJournalItem
	EventNewLaborerItem
	EventNewEquipmentItemLegendarySoul
	EventNewSimpleHarvestableObject
	EventNewSimpleHarvestableObjectList
	EventNewHarvestableObject
	EventNewTreasureDestinationObject
	EventTreasureDestinationObjectStatus
	EventCloseTreasureDestinationObject
	EventNewSilverObject
	EventNewBuilding
	EventHarvestableChangeState
	EventMobChangeState
	EventFactionBuildingInfo
	EventCraftBuildingInfo
	EventRepairBuildingInfo
	EventMeldBuildingInfo
	EventConstructionSiteInfo
	EventPlayerBuildingInfo
	EventFarmBuildingInfo
	EventTutorialBuildingInfo
	EventLaborerObjectInfo
	EventLaborerObjectJobInfo
	EventMarketPlaceBuildingInfo
	EventHarvestStart
	EventHarvestCancel
	EventHarvestFinished
	EventTakeSilver
	EventRemoveSilver
	EventActionOnBuildingStart
	EventActionOnBuildingCancel
	EventActionOnBuildingFinished
	EventItemRerollQualityFinished
	EventInstallResourceStart
	EventInstallResourceCancel
	EventInstallResourceFinished
	EventCraftItemFinished
	EventLogoutCancel
	EventChatMessage
	EventChatSay
	EventChatWhisper
	EventChatMuted
	EventPlayEmote
	EventStopEmote
	EventSystemMessage
	EventUtilityTextMessage
	EventUpdateMoney
	EventUpdateFame
	EventUpdateLearningPoints
	EventUpdateReSpecPoints
	EventUpdateCurrency
	EventUpdateFactionStanding
	EventUpdateStanding
	EventRespawn
	EventServerDebugLog
	EventCharacterEquipmentChanged
	EventRegenerationHealthChanged
	EventRegenerationEnergyChanged
	EventRegenerationMountHealthChanged
	EventRegenerationCraftingChanged
	EventRegenerationHealthEnergyComboChanged
	EventRegenerationPlayerComboChanged
	EventDurabilityChanged
	EventNewLoot
	EventAttachItemContainer
	EventDetachItemContainer
	EventInvalidateItemContainer
	EventLockItemContainer
	EventGuildUpdate
	EventGuildPlayerUpdated
	EventInvitedToGuild
	EventGuildMemberWorldUpdate
	EventUpdateMatchDetails
	EventObjectEvent
	EventNewMonolithObject
	EventMonolithHasBannersPlacedUpdate
	EventNewOrbObject
	EventNewCastleObject
	EventNewSpellEffectArea
	EventUpdateSpellEffectArea
	EventNewChainSpell
	EventUpdateChainSpell
	EventNewTreasureChest
	EventStartMatch
	EventStartArenaMatchInfos
	EventEndArenaMatch
	EventMatchUpdate
	EventActiveMatchUpdate
	EventNewMob
	EventDebugAggroInfo
	EventDebugVariablesInfo
	EventDebugReputationInfo
	EventDebugDiminishingReturnInfo
	EventDebugSmartClusterQueueInfo
	EventClaimOrbStart
	EventClaimOrbFinished
	EventClaimOrbCancel
	EventOrbUpdate
	EventOrbClaimed
	EventOrbReset
	EventNewWarCampObject
	EventNewMatchLootChestObject
	EventNewArenaExit
	EventGuildMemberTerritoryUpdate
	EventInvitedMercenaryToMatch
	EventClusterInfoUpdate
	EventForcedMovement
	EventForcedMovementCancel
	EventCharacterStats
	EventCharacterStatsKillHistory
	EventCharacterStatsDeathHistory
	EventCharacterStatsKnockDownHistory
	EventCharacterStatsKnockedDownHistory
	EventGuildStats
	EventKillHistoryDetails
	EventItemKillHistoryDetails
	EventFullAchievementInfo
	EventFinishedAchievement
	EventAchievementProgressInfo
	EventFullAchievementProgressInfo
	EventFullTrackedAchievementInfo
	EventFullAutoLearnAchievementInfo
	EventQuestGiverQuestOffered
	EventQuestGiverDebugInfo
	EventConsoleEvent
	EventTimeSync
	EventChangeAvatar
	EventChangeMountSkin
	EventGameEvent
	EventKilledPlayer
	EventDied
	EventKnockedDown
	EventUnconcious
	EventMatchPlayerJoinedEvent
	EventMatchPlayerStatsEvent
	EventMatchPlayerStatsCompleteEvent
	EventMatchTimeLineEventEvent
	EventMatchNewCombatRound
	EventMatchEndCombatRound
	EventMatchPlayerMainGearStatsEvent
	EventMatchPlayerChangedAvatarEvent
	EventInvitationPlayerTrade
	EventPlayerTradeStart
	EventPlayerTradeCancel
	EventPlayerTradeUpdate
	EventPlayerTradeFinished
	EventPlayerTradeAcceptChange
	EventMiniMapPing
	EventMarketPlaceNotification
	EventDuellingChallengePlayer
	EventNewDuellingPost
	EventDuelStarted
	EventDuelEnded
	EventDuelDenied
	EventDuelRequestCanceled
	EventDuelLeftArea
	EventDuelReEnteredArea
	EventNewRealEstate
	EventMiniMapOwnedBuildingsPositions
	EventRealEstateListUpdate
	EventGuildLogoUpdate
	EventGuildLogoChanged
	EventPlaceableObjectPlace
	EventPlaceableObjectPlaceCancel
	EventFurnitureObjectBuffProviderInfo
	EventFurnitureObjectCheatProviderInfo
	EventFarmableObjectInfo
	EventNewUnreadMails
	EventMailOperationPossible
	EventGuildLogoObjectUpdate
	EventStartLogout
	EventNewChatChannels
	EventJoinedChatChannel
	EventLeftChatChannel
	EventRemovedChatChannel
	EventAccessStatus
	EventMounted
	EventMountStart
	EventMountCancel
	EventNewTravelpoint
	EventNewIslandAccessPoint
	EventNewExit
	EventUpdateHome
	EventUpdateChatSettings
	EventResurrectionOffer
	EventResurrectionReply
	EventLootEquipmentChanged
	EventUpdateUnlockedGuildLogos
	EventUpdateUnlockedAvatars
	EventUpdateUnlockedAvatarRings
	EventUpdateUnlockedBuildings
	EventNewIslandManagement
	EventNewTeleportStone
	EventCloak
	EventPartyInvitation
	EventPartyJoinRequest
	EventPartyJoined
	EventPartyDisbanded
	EventPartyPlayerJoined
	EventPartyChangedOrder
	EventPartyPlayerLeft
	EventPartyLeaderChanged
	EventPartyLootSettingChangedPlayer
	EventPartySilverGained
	EventPartyPlayerUpdated
	EventPartyInvitationAnswer
	EventPartyJoinRequestAnswer
	EventPartyMarkedObjectsUpdated
	EventPartyOnClusterPartyJoined
	EventPartySetRoleFlag
	EventPartyInviteOrJoinPlayerEquipmentInfo
	EventPartyReadyCheckUpdate
	EventPartyFactionWarfareReinforcementSettingChangedPlayer
	EventSpellCooldownUpdate
	EventNewHellgateExitPortal
	EventNewExpeditionExit
	EventNewExpeditionNarrator
	EventExitEnterStart
	EventExitEnterCancel
	EventExitEnterFinished
	EventNewQuestGiverObject
	EventFullQuestInfo
	EventQuestProgressInfo
	EventQuestGiverInfoForPlayer
	EventFullExpeditionInfo
	EventExpeditionQuestProgressInfo
	EventInvitedToExpedition
	EventExpeditionRegistrationInfo
	EventEnteringExpeditionStart
	EventEnteringExpeditionCancel
	EventRewardGranted
	EventArenaRegistrationInfo
	EventEnteringArenaStart
	EventEnteringArenaCancel
	EventEnteringArenaLockStart
	EventEnteringArenaLockCancel
	EventInvitedToArenaMatch
	EventUsingHellgateShrine
	EventEnteringHellgateLockStart
	EventEnteringHellgateLockCancel
	EventPlayerCounts
	EventInCombatStateUpdate
	EventOtherGrabbedLoot
	EventTreasureChestUsingStart
	EventTreasureChestUsingFinished
	EventTreasureChestUsingCancel
	EventTreasureChestUsingOpeningComplete
	EventTreasureChestForceCloseInventory
	EventLocalTreasuresUpdate
	EventLootChestSpawnpointsUpdate
	EventPremiumChanged
	EventPremiumExtended
	EventPremiumLifeTimeRewardGained
	EventGoldPurchased
	EventLaborerGotUpgraded
	EventJournalGotFull
	EventJournalFillError
	EventFriendRequest
	EventFriendRequestInfos
	EventFriendInfos
	EventFriendRequestAnswered
	EventFriendOnlineStatus
	EventFriendRequestCanceled
	EventFriendRemoved
	EventFriendUpdated
	EventPartyLootItems
	EventPartyLootItemsRemoved
	EventPartyLootItemTypesRemoved
	EventReputationUpdate
	EventDefenseUnitAttackBegin
	EventDefenseUnitAttackEnd
	EventDefenseUnitAttackDamage
	EventUnrestrictedPvpZoneUpdate
	EventUnrestrictedPvpZoneStatus
	EventReputationImplicationUpdate
	EventNewMountObject
	EventMountHealthUpdate
	EventMountCooldownUpdate
	EventNewExpeditionAgent
	EventNewExpeditionCheckPoint
	EventExpeditionStartEvent
	EventVoteEvent
	EventRatingEvent
	EventNewArenaAgent
	EventBoostFarmable
	EventUseFunction
	EventNewPortalEntrance
	EventNewPortalExit
	EventNewRandomDungeonExit
	EventWaitingQueueUpdate
	EventPlayerMovementRateUpdate
	EventObserveStart
	EventMinimapZergs
	EventMinimapSmartClusterZergs
	EventPaymentTransactions
	EventPerformanceStatsUpdate
	EventOverloadModeUpdate
	EventDebugDrawEvent
	EventRecordCameraMove
	EventRecordStart
	EventClaimPowerCrystalStart
	EventClaimPowerCrystalCancel
	EventClaimPowerCrystalReset
	EventClaimPowerCrystalFinished
	EventTerritoryClaimStart
	EventTerritoryClaimCancel
	EventTerritoryClaimFinished
	EventTerritoryScheduleResult
	EventTerritoryUpgradeWithPowerCrystalResult
	EventReturningPowerCrystalStart
	EventReturningPowerCrystalFinished
	EventUpdateAccountState
	EventStartDeterministicRoam
	EventGuildFullAccessTagsUpdated
	EventGuildAccessTagUpdated
	EventGvgSeasonUpdate
	EventGvgSeasonCheatCommand
	EventSeasonPointsByKillingBooster
	EventFishingStart
	EventFishingCast
	EventFishingCatch
	EventFishingFinished
	EventFishingCancel
	EventNewFloatObject
	EventNewFishingZoneObject
	EventFishingMiniGame
	EventSteamAchievementCompleted
	EventUpdatePuppet
	EventChangeFlaggingFinished
	EventNewOutpostObject
	EventOutpostUpdate
	EventOutpostClaimed
	EventOverChargeEnd
	EventOverChargeStatus
	EventPartyFinderFullUpdate
	EventPartyFinderUpdate
	EventPartyFinderApplicantsUpdate
	EventPartyFinderEquipmentSnapshot
	EventPartyFinderJoinRequestDeclined
	EventNewUnlockedPersonalSeasonRewards
	EventPersonalSeasonPointsGained
	EventPersonalSeasonPastSeasonDataEvent
	EventMatchLootChestOpeningStart
	EventMatchLootChestOpeningFinished
	EventMatchLootChestOpeningCancel
	EventNotifyCrystalMatchReward
	EventCrystalRealmFeedback
	EventNewLocationMarker
	EventNewTutorialBlocker
	EventNewTileSwitch
	EventNewInformationProvider
	EventNewDynamicGuildLogo
	EventNewDecoration
	EventTutorialUpdate
	EventTriggerHintBox
	EventRandomDungeonPositionInfo
	EventNewLootChest
	EventUpdateLootChest
	EventLootChestOpened
	EventUpdateLootProtectedByMobsWithMinimapDisplay
	EventNewShrine
	EventUpdateShrine
	EventUpdateRoom
	EventNewMobSoul
	EventNewHellgateShrine
	EventUpdateHellgateShrine
	EventActivateHellgateExit
	EventMutePlayerUpdate
	EventShopTileUpdate
	EventShopUpdate
	EventEasyAntiCheatKick
	EventBattlEyeServerMessage
	EventUnlockVanityUnlock
	EventAvatarUnlocked
	EventCustomizationChanged
	EventBaseVaultInfo
	EventGuildVaultInfo
	EventBankVaultInfo
	EventRecoveryVaultPlayerInfo
	EventRecoveryVaultGuildInfo
	EventUpdateWardrobe
	EventCastlePhaseChanged
	EventGuildAccountLogEvent
	EventNewHideoutObject
	EventNewHideoutManagement
	EventNewHideoutExit
	EventInitHideoutAttackStart
	EventInitHideoutAttackCancel
	EventInitHideoutAttackFinished
	EventHideoutManagementUpdate
	EventHideoutUpgradeWithPowerCrystalResult
	EventIpChanged
	EventSmartClusterQueueUpdateInfo
	EventSmartClusterQueueActiveInfo
	EventSmartClusterQueueKickWarning
	EventSmartClusterQueueInvite
	EventReceivedGvgSeasonPoints
	EventTowerPowerPointUpdate
	EventOpenWorldAttackScheduleStart
	EventOpenWorldAttackScheduleFinished
	EventOpenWorldAttackScheduleCancel
	EventOpenWorldAttackConquerStart
	EventOpenWorldAttackConquerFinished
	EventOpenWorldAttackConquerCancel
	EventOpenWorldAttackConquerStatus
	EventOpenWorldAttackStart
	EventOpenWorldAttackEnd
	EventNewRandomResourceBlocker
	EventNewHomeObject
	EventHideoutObjectUpdate
	EventUpdateInfamy
	EventMinimapPositionMarkers
	EventNewTunnelExit
	EventCorruptedDungeonUpdate
	EventCorruptedDungeonStatus
	EventCorruptedDungeonInfamy
	EventHellgateRestrictedAreaUpdate
	EventHellgateInfamy
	EventHellgateStatus
	EventHellgateStatusUpdate
	EventHellgateSuspense
	EventReplaceSpellSlotWithMultiSpell
	EventNewCorruptedShrine
	EventUpdateCorruptedShrine
	EventCorruptedShrineUsageStart
	EventCorruptedShrineUsageCancel
	EventExitUsed
	EventLinkedToObject
	EventLinkToObjectBroken
	EventEstimatedMarketValueUpdate
	EventStuckCancel
	EventDungonEscapeReady
	EventFactionWarfareClusterState
	EventFactionWarfareHasUnclaimedWeeklyReportsEvent
	EventSimpleFeedback
	EventSmartClusterQueueSkipClusterError
	EventXignCodeEvent
	EventBatchUseItemStart
	EventBatchUseItemEnd
	EventRedZonePlayerNotification
	EventRedZoneEventCheatCleanup
	EventRedZoneFortressEventChestOpened
	EventRedZoneWorldEvent
	EventFactionWarfareStats
	EventUpdateFactionBalanceFactors
	EventFactionEnlistmentChanged
	EventUpdateFactionRank
	EventFactionWarfareCampaignRewardsUnlocked
	EventFeaturedFeatureUpdate
	EventNewPowerCrystalObject
	EventMinimapCrystalPositionMarker
	EventCarryPowerCrystalUpdate
	EventPickupPowerCrystalStart
	EventPickupPowerCrystalCancel
	EventPickupPowerCrystalFinished
	EventDoSimpleActionStart
	EventDoSimpleActionCancel
	EventDoSimpleActionFinished
	EventNotifyGuestAccountVerified
	EventMightAndFavorReceivedEvent
	EventWeeklyPvpChallengeRewardStateUpdate
	EventNewUnlockedPvpSeasonChallengeRewards
	EventStaticDungeonEntrancesDungeonEventStatusUpdates
	EventStaticDungeonDungeonValueUpdate
	EventStaticDungeonEntranceDungeonEventsAborted
	EventInAppPurchaseConfirmedGooglePlay
	EventFeatureSwitchInfo
	EventPartyJoinRequestAborted
	EventPartyInviteAborted
	EventPartyStartHuntRequest
	EventPartyStartHuntRequested
	EventPartyStartHuntRequestAnswer
	EventPartyPlayerLeaveScheduled
	EventGuildInviteDeclined
	EventCancelMultiSpellSlots
	EventNewVisualEventObject
	EventCastleClaimProgress
	EventCastleClaimProgressLogo
	EventTownPortalUpdateState
	EventTownPortalFailed
	EventConsumableVanityChargesAdded
	EventFestivitiesUpdate
	EventNewBannerObject
	EventNewMistsImmediateReturnExit
	EventMistsPlayerJoinedInfo
	EventNewMistsStaticEntrance
	EventNewMistsOpenWorldExit
	EventNewTunnelExitTemp
	EventNewMistsWispSpawn
	EventMistsWispSpawnStateChange
	EventNewMistsCityEntrance
	EventNewMistsCityRoadsEntrance
	EventMistsCityRoadsEntrancePartyStateUpdate
	EventMistsCityRoadsEntranceClearStateForParty
	EventMistsEntranceDataChanged
	EventNewCagedObject
	EventCagedObjectStateUpdated
	EventEntrancePartyBindingCreated
	EventEntrancePartyBindingCleared
	EventEntrancePartyBindingInfos
	EventNewMistsBorderExit
	EventNewMistsDungeonExit
	EventLocalQuestInfos
	EventLocalQuestStarted
	EventLocalQuestActive
	EventLocalQuestInactive
	EventLocalQuestProgressUpdate
	EventNewUnrestrictedPvpZone
	EventTemporaryFlaggingStatusUpdate
	EventSpellTestPerformanceUpdate
	EventTransformation
	EventTransformationEnd
	EventUpdateTrustlevel
	EventRevealHiddenTimeStamps
	EventModifyItemTraitFinished
	EventRerollItemTraitValueFinished
	EventHuntQuestProgressInfo
	EventHuntStarted
	EventHuntFinished
	EventHuntAborted
	EventHuntMissionStepStateUpdate
	EventNewHuntTrack
	EventHuntMissionUpdate
	EventHuntQuestMissionProgressUpdate
	EventHuntTrackUsed
	EventHuntTrackUseableAgain
	EventMinimapHuntTrackMarkers
	EventNoTracksFound
	EventHuntQuestAborted
	EventInteractWithTrackStart
	EventInteractWithTrackCancel
	EventInteractWithTrackFinished
	EventNewDynamicCompound
	EventLegendaryItemDestroyed
	EventAttunementInfo
	EventTerritoryClaimRaidedRawEnergyCrystalResult
	EventCarriedObjectExpiryWarning
	EventCarriedObjectExpired
	EventTerritoryRaidStart
	EventTerritoryRaidCancel
	EventTerritoryRaidFinished
	EventTerritoryRaidResult
	EventTerritoryMonolithActiveRaidStatus
	EventTerritoryMonolithActiveRaidCancelled
	EventMonolithEnergyStorageUpdate
	EventMonolithNextScheduledOpenWorldAttackUpdate
	EventMonolithProtectedBuildingsDamageReductionUpdate
	EventNewBuildingBaseEvent
	EventNewFortificationBuilding
	EventNewCastleGateBuilding
	EventBuildingDurabilityUpdate
	EventMonolithFortificationPointsUpdate
	EventFortificationBuildingUpgradeInfo
	EventFortificationBuildingsDamageStateUpdate
	EventSiegeNotificationEvent
	EventUpdateEnemyWarBannerActive
	EventTerritoryAnnouncePlayerEjection
	EventCastleGateSwitchUseStarted
	EventCastleGateSwitchUseFinished
	EventFortificationBuildingWillDowngrade
	EventBotCommand
	EventJournalAchievementProgressUpdate
	EventJournalClaimableRewardUpdate
	EventKeySync
	EventLocalQuestAreaGone
	EventDynamicTemplate
	EventDynamicTemplateForcedStateChange
	EventNewOutlandsTeleportationPortal
	EventNewOutlandsTeleportationReturnPortal
	EventOutlandsTeleportationBindingCleared
	EventOutlandsTeleportationReturnPortalUpdateEvent
	EventPlayerUsedOutlandsTeleportationPortal
	EventEncumberedRestricted
	EventNewPiledObject
	EventPiledObjectStateChanged
	EventNewSmugglerCrateDeliveryStation
	EventKillRewardedNoFame
	EventPickupFromPiledObjectStart
	EventPickupFromPiledObjectCancel
	EventPickupFromPiledObjectReset
	EventPickupFromPiledObjectFinished
	EventArmoryActivityChange
	EventNewKillTrophyFurnitureBuilding
	EventHellDungeonsPlayerJoinedInfo
	EventNewTileSwitchTrigger
	EventNewMultiRewardObject
	EventNewHellDungeonSoulShrineObject
	EventHellDungeonSoulShrineStateUpdate
	EventNewResurrectionShrine
	EventUpdateResurrectionShrine
	EventStandTimeFinished
	EventEpicAchievementAndStatsUpdate
	EventSpectateTargetAfterDeathUpdate
	EventSpectateTargetAfterDeathEnded
	EventNewHellDungeonUpwardExit
	EventNewHellDungeonSoulExit
	EventNewHellDungeonDownwardExit
	EventNewHellDungeonChestExit
	EventNewCorruptedStaticEntrance
	EventNewHellDungeonStaticEntrance
	EventUpdateHellDungeonStaticEntranceState
	EventDebugTriggerHellDungeonShutdownStart
	EventFullJournalQuestInfo
	EventJournalQuestProgressInfo
	EventNewHellDungeonRoomShrineObject
	EventHellDungeonRoomShrineStateUpdate
	EventSimpleBehaviourBuildingStateUpdate
	EventSetTimeScaling
	EventStopTimeScaling
	EventKeyValidation
	EventPlayerJoinMapMarkerTimerStates
	EventNewMapMarkerTimer
	EventRemoveMapMarkerTimer
	EventNewFactionFortressObject
	EventFactionFortressAnnouncePlayerEjection
	EventRewardFactionWarfareSupply
	EventFactionCaptureAreaProgressUpdate
	EventFactionFortressClaimed
	EventFactionFortressWeaponCachesSpawned
	EventFactionFortressWeaponCacheClaimed
	EventFactionFortressFightStateUpdate
	EventFactionFortressCutoffFightStateUpdate
	EventFactionFortressFightEnded
	EventNewFactionWarfarePortal
	EventFactionPortalTargetUpdate
	EventFactionFortressFightStartedInRemoteClusterEvent
	EventFactionFortressFightFinishedInRemoteClusterEvent
	EventFactionDuchySupplyWarDefensiveVictoryEvent
	EventFactionDuchyReconnectedFromCutoffEvent
	EventFactionFortressCutoffFightCancelledByClusterOwnerChangeEvent
	EventFactionDuchyEnteredCutoffStateEvent
	EventLeaveProtectionStateUpdate
	EventRedZoneEventStandings
	EventNewFactionBattleStandardDeliveryStation
	EventNewLoreSnippetObject
	EventLoreSnippetObjectStateUpdate
	EventLoreSnippedClaimed
	EventLoreSnippetStatesChangedByCheat
	EventNewTeleporterNode
	EventTeleporterNodeStateChanged
	EventTeleporterConnectionsFullStateUpdate
	EventTeleporterConnectionStateChanged
	EventRetrieveCarriableObjectStart
	EventRetrieveCarriableObjectCancel
	EventRetrieveCarriableObjectReset
	EventRetrieveCarriableObjectFinished
	EventLosingCarriableObjectStart
	EventLosingCarriableObjectFinished
)

// EventName returns the C# identifier for a code, or empty if unknown.
func EventName(c Event) string {
	if c < 0 || int(c) >= len(EventNames) { return "" }
	return EventNames[c]
}

var EventNames = [...]string{
	"Unused",
	"Leave",
	"JoinFinished",
	"Move",
	"Teleport",
	"ChangeEquipment",
	"HealthUpdate",
	"HealthUpdates",
	"EnergyUpdate",
	"DamageShieldUpdate",
	"CraftingFocusUpdate",
	"ActiveSpellEffectsUpdate",
	"ResetCooldowns",
	"Attack",
	"CastStart",
	"ChannelingUpdate",
	"CastCancel",
	"CastTimeUpdate",
	"CastFinished",
	"CastSpell",
	"CastSpells",
	"CastHit",
	"CastHits",
	"StoredTargetsUpdate",
	"ChannelingEnded",
	"AttackBuilding",
	"InventoryPutItem",
	"InventoryDeleteItem",
	"InventoryState",
	"NewCharacter",
	"NewEquipmentItem",
	"NewSiegeBannerItem",
	"NewSimpleItem",
	"NewFurnitureItem",
	"NewKillTrophyItem",
	"NewJournalItem",
	"NewLaborerItem",
	"NewEquipmentItemLegendarySoul",
	"NewSimpleHarvestableObject",
	"NewSimpleHarvestableObjectList",
	"NewHarvestableObject",
	"NewTreasureDestinationObject",
	"TreasureDestinationObjectStatus",
	"CloseTreasureDestinationObject",
	"NewSilverObject",
	"NewBuilding",
	"HarvestableChangeState",
	"MobChangeState",
	"FactionBuildingInfo",
	"CraftBuildingInfo",
	"RepairBuildingInfo",
	"MeldBuildingInfo",
	"ConstructionSiteInfo",
	"PlayerBuildingInfo",
	"FarmBuildingInfo",
	"TutorialBuildingInfo",
	"LaborerObjectInfo",
	"LaborerObjectJobInfo",
	"MarketPlaceBuildingInfo",
	"HarvestStart",
	"HarvestCancel",
	"HarvestFinished",
	"TakeSilver",
	"RemoveSilver",
	"ActionOnBuildingStart",
	"ActionOnBuildingCancel",
	"ActionOnBuildingFinished",
	"ItemRerollQualityFinished",
	"InstallResourceStart",
	"InstallResourceCancel",
	"InstallResourceFinished",
	"CraftItemFinished",
	"LogoutCancel",
	"ChatMessage",
	"ChatSay",
	"ChatWhisper",
	"ChatMuted",
	"PlayEmote",
	"StopEmote",
	"SystemMessage",
	"UtilityTextMessage",
	"UpdateMoney",
	"UpdateFame",
	"UpdateLearningPoints",
	"UpdateReSpecPoints",
	"UpdateCurrency",
	"UpdateFactionStanding",
	"UpdateStanding",
	"Respawn",
	"ServerDebugLog",
	"CharacterEquipmentChanged",
	"RegenerationHealthChanged",
	"RegenerationEnergyChanged",
	"RegenerationMountHealthChanged",
	"RegenerationCraftingChanged",
	"RegenerationHealthEnergyComboChanged",
	"RegenerationPlayerComboChanged",
	"DurabilityChanged",
	"NewLoot",
	"AttachItemContainer",
	"DetachItemContainer",
	"InvalidateItemContainer",
	"LockItemContainer",
	"GuildUpdate",
	"GuildPlayerUpdated",
	"InvitedToGuild",
	"GuildMemberWorldUpdate",
	"UpdateMatchDetails",
	"ObjectEvent",
	"NewMonolithObject",
	"MonolithHasBannersPlacedUpdate",
	"NewOrbObject",
	"NewCastleObject",
	"NewSpellEffectArea",
	"UpdateSpellEffectArea",
	"NewChainSpell",
	"UpdateChainSpell",
	"NewTreasureChest",
	"StartMatch",
	"StartArenaMatchInfos",
	"EndArenaMatch",
	"MatchUpdate",
	"ActiveMatchUpdate",
	"NewMob",
	"DebugAggroInfo",
	"DebugVariablesInfo",
	"DebugReputationInfo",
	"DebugDiminishingReturnInfo",
	"DebugSmartClusterQueueInfo",
	"ClaimOrbStart",
	"ClaimOrbFinished",
	"ClaimOrbCancel",
	"OrbUpdate",
	"OrbClaimed",
	"OrbReset",
	"NewWarCampObject",
	"NewMatchLootChestObject",
	"NewArenaExit",
	"GuildMemberTerritoryUpdate",
	"InvitedMercenaryToMatch",
	"ClusterInfoUpdate",
	"ForcedMovement",
	"ForcedMovementCancel",
	"CharacterStats",
	"CharacterStatsKillHistory",
	"CharacterStatsDeathHistory",
	"CharacterStatsKnockDownHistory",
	"CharacterStatsKnockedDownHistory",
	"GuildStats",
	"KillHistoryDetails",
	"ItemKillHistoryDetails",
	"FullAchievementInfo",
	"FinishedAchievement",
	"AchievementProgressInfo",
	"FullAchievementProgressInfo",
	"FullTrackedAchievementInfo",
	"FullAutoLearnAchievementInfo",
	"QuestGiverQuestOffered",
	"QuestGiverDebugInfo",
	"ConsoleEvent",
	"TimeSync",
	"ChangeAvatar",
	"ChangeMountSkin",
	"GameEvent",
	"KilledPlayer",
	"Died",
	"KnockedDown",
	"Unconcious",
	"MatchPlayerJoinedEvent",
	"MatchPlayerStatsEvent",
	"MatchPlayerStatsCompleteEvent",
	"MatchTimeLineEventEvent",
	"MatchNewCombatRound",
	"MatchEndCombatRound",
	"MatchPlayerMainGearStatsEvent",
	"MatchPlayerChangedAvatarEvent",
	"InvitationPlayerTrade",
	"PlayerTradeStart",
	"PlayerTradeCancel",
	"PlayerTradeUpdate",
	"PlayerTradeFinished",
	"PlayerTradeAcceptChange",
	"MiniMapPing",
	"MarketPlaceNotification",
	"DuellingChallengePlayer",
	"NewDuellingPost",
	"DuelStarted",
	"DuelEnded",
	"DuelDenied",
	"DuelRequestCanceled",
	"DuelLeftArea",
	"DuelReEnteredArea",
	"NewRealEstate",
	"MiniMapOwnedBuildingsPositions",
	"RealEstateListUpdate",
	"GuildLogoUpdate",
	"GuildLogoChanged",
	"PlaceableObjectPlace",
	"PlaceableObjectPlaceCancel",
	"FurnitureObjectBuffProviderInfo",
	"FurnitureObjectCheatProviderInfo",
	"FarmableObjectInfo",
	"NewUnreadMails",
	"MailOperationPossible",
	"GuildLogoObjectUpdate",
	"StartLogout",
	"NewChatChannels",
	"JoinedChatChannel",
	"LeftChatChannel",
	"RemovedChatChannel",
	"AccessStatus",
	"Mounted",
	"MountStart",
	"MountCancel",
	"NewTravelpoint",
	"NewIslandAccessPoint",
	"NewExit",
	"UpdateHome",
	"UpdateChatSettings",
	"ResurrectionOffer",
	"ResurrectionReply",
	"LootEquipmentChanged",
	"UpdateUnlockedGuildLogos",
	"UpdateUnlockedAvatars",
	"UpdateUnlockedAvatarRings",
	"UpdateUnlockedBuildings",
	"NewIslandManagement",
	"NewTeleportStone",
	"Cloak",
	"PartyInvitation",
	"PartyJoinRequest",
	"PartyJoined",
	"PartyDisbanded",
	"PartyPlayerJoined",
	"PartyChangedOrder",
	"PartyPlayerLeft",
	"PartyLeaderChanged",
	"PartyLootSettingChangedPlayer",
	"PartySilverGained",
	"PartyPlayerUpdated",
	"PartyInvitationAnswer",
	"PartyJoinRequestAnswer",
	"PartyMarkedObjectsUpdated",
	"PartyOnClusterPartyJoined",
	"PartySetRoleFlag",
	"PartyInviteOrJoinPlayerEquipmentInfo",
	"PartyReadyCheckUpdate",
	"PartyFactionWarfareReinforcementSettingChangedPlayer",
	"SpellCooldownUpdate",
	"NewHellgateExitPortal",
	"NewExpeditionExit",
	"NewExpeditionNarrator",
	"ExitEnterStart",
	"ExitEnterCancel",
	"ExitEnterFinished",
	"NewQuestGiverObject",
	"FullQuestInfo",
	"QuestProgressInfo",
	"QuestGiverInfoForPlayer",
	"FullExpeditionInfo",
	"ExpeditionQuestProgressInfo",
	"InvitedToExpedition",
	"ExpeditionRegistrationInfo",
	"EnteringExpeditionStart",
	"EnteringExpeditionCancel",
	"RewardGranted",
	"ArenaRegistrationInfo",
	"EnteringArenaStart",
	"EnteringArenaCancel",
	"EnteringArenaLockStart",
	"EnteringArenaLockCancel",
	"InvitedToArenaMatch",
	"UsingHellgateShrine",
	"EnteringHellgateLockStart",
	"EnteringHellgateLockCancel",
	"PlayerCounts",
	"InCombatStateUpdate",
	"OtherGrabbedLoot",
	"TreasureChestUsingStart",
	"TreasureChestUsingFinished",
	"TreasureChestUsingCancel",
	"TreasureChestUsingOpeningComplete",
	"TreasureChestForceCloseInventory",
	"LocalTreasuresUpdate",
	"LootChestSpawnpointsUpdate",
	"PremiumChanged",
	"PremiumExtended",
	"PremiumLifeTimeRewardGained",
	"GoldPurchased",
	"LaborerGotUpgraded",
	"JournalGotFull",
	"JournalFillError",
	"FriendRequest",
	"FriendRequestInfos",
	"FriendInfos",
	"FriendRequestAnswered",
	"FriendOnlineStatus",
	"FriendRequestCanceled",
	"FriendRemoved",
	"FriendUpdated",
	"PartyLootItems",
	"PartyLootItemsRemoved",
	"PartyLootItemTypesRemoved",
	"ReputationUpdate",
	"DefenseUnitAttackBegin",
	"DefenseUnitAttackEnd",
	"DefenseUnitAttackDamage",
	"UnrestrictedPvpZoneUpdate",
	"UnrestrictedPvpZoneStatus",
	"ReputationImplicationUpdate",
	"NewMountObject",
	"MountHealthUpdate",
	"MountCooldownUpdate",
	"NewExpeditionAgent",
	"NewExpeditionCheckPoint",
	"ExpeditionStartEvent",
	"VoteEvent",
	"RatingEvent",
	"NewArenaAgent",
	"BoostFarmable",
	"UseFunction",
	"NewPortalEntrance",
	"NewPortalExit",
	"NewRandomDungeonExit",
	"WaitingQueueUpdate",
	"PlayerMovementRateUpdate",
	"ObserveStart",
	"MinimapZergs",
	"MinimapSmartClusterZergs",
	"PaymentTransactions",
	"PerformanceStatsUpdate",
	"OverloadModeUpdate",
	"DebugDrawEvent",
	"RecordCameraMove",
	"RecordStart",
	"ClaimPowerCrystalStart",
	"ClaimPowerCrystalCancel",
	"ClaimPowerCrystalReset",
	"ClaimPowerCrystalFinished",
	"TerritoryClaimStart",
	"TerritoryClaimCancel",
	"TerritoryClaimFinished",
	"TerritoryScheduleResult",
	"TerritoryUpgradeWithPowerCrystalResult",
	"ReturningPowerCrystalStart",
	"ReturningPowerCrystalFinished",
	"UpdateAccountState",
	"StartDeterministicRoam",
	"GuildFullAccessTagsUpdated",
	"GuildAccessTagUpdated",
	"GvgSeasonUpdate",
	"GvgSeasonCheatCommand",
	"SeasonPointsByKillingBooster",
	"FishingStart",
	"FishingCast",
	"FishingCatch",
	"FishingFinished",
	"FishingCancel",
	"NewFloatObject",
	"NewFishingZoneObject",
	"FishingMiniGame",
	"SteamAchievementCompleted",
	"UpdatePuppet",
	"ChangeFlaggingFinished",
	"NewOutpostObject",
	"OutpostUpdate",
	"OutpostClaimed",
	"OverChargeEnd",
	"OverChargeStatus",
	"PartyFinderFullUpdate",
	"PartyFinderUpdate",
	"PartyFinderApplicantsUpdate",
	"PartyFinderEquipmentSnapshot",
	"PartyFinderJoinRequestDeclined",
	"NewUnlockedPersonalSeasonRewards",
	"PersonalSeasonPointsGained",
	"PersonalSeasonPastSeasonDataEvent",
	"MatchLootChestOpeningStart",
	"MatchLootChestOpeningFinished",
	"MatchLootChestOpeningCancel",
	"NotifyCrystalMatchReward",
	"CrystalRealmFeedback",
	"NewLocationMarker",
	"NewTutorialBlocker",
	"NewTileSwitch",
	"NewInformationProvider",
	"NewDynamicGuildLogo",
	"NewDecoration",
	"TutorialUpdate",
	"TriggerHintBox",
	"RandomDungeonPositionInfo",
	"NewLootChest",
	"UpdateLootChest",
	"LootChestOpened",
	"UpdateLootProtectedByMobsWithMinimapDisplay",
	"NewShrine",
	"UpdateShrine",
	"UpdateRoom",
	"NewMobSoul",
	"NewHellgateShrine",
	"UpdateHellgateShrine",
	"ActivateHellgateExit",
	"MutePlayerUpdate",
	"ShopTileUpdate",
	"ShopUpdate",
	"EasyAntiCheatKick",
	"BattlEyeServerMessage",
	"UnlockVanityUnlock",
	"AvatarUnlocked",
	"CustomizationChanged",
	"BaseVaultInfo",
	"GuildVaultInfo",
	"BankVaultInfo",
	"RecoveryVaultPlayerInfo",
	"RecoveryVaultGuildInfo",
	"UpdateWardrobe",
	"CastlePhaseChanged",
	"GuildAccountLogEvent",
	"NewHideoutObject",
	"NewHideoutManagement",
	"NewHideoutExit",
	"InitHideoutAttackStart",
	"InitHideoutAttackCancel",
	"InitHideoutAttackFinished",
	"HideoutManagementUpdate",
	"HideoutUpgradeWithPowerCrystalResult",
	"IpChanged",
	"SmartClusterQueueUpdateInfo",
	"SmartClusterQueueActiveInfo",
	"SmartClusterQueueKickWarning",
	"SmartClusterQueueInvite",
	"ReceivedGvgSeasonPoints",
	"TowerPowerPointUpdate",
	"OpenWorldAttackScheduleStart",
	"OpenWorldAttackScheduleFinished",
	"OpenWorldAttackScheduleCancel",
	"OpenWorldAttackConquerStart",
	"OpenWorldAttackConquerFinished",
	"OpenWorldAttackConquerCancel",
	"OpenWorldAttackConquerStatus",
	"OpenWorldAttackStart",
	"OpenWorldAttackEnd",
	"NewRandomResourceBlocker",
	"NewHomeObject",
	"HideoutObjectUpdate",
	"UpdateInfamy",
	"MinimapPositionMarkers",
	"NewTunnelExit",
	"CorruptedDungeonUpdate",
	"CorruptedDungeonStatus",
	"CorruptedDungeonInfamy",
	"HellgateRestrictedAreaUpdate",
	"HellgateInfamy",
	"HellgateStatus",
	"HellgateStatusUpdate",
	"HellgateSuspense",
	"ReplaceSpellSlotWithMultiSpell",
	"NewCorruptedShrine",
	"UpdateCorruptedShrine",
	"CorruptedShrineUsageStart",
	"CorruptedShrineUsageCancel",
	"ExitUsed",
	"LinkedToObject",
	"LinkToObjectBroken",
	"EstimatedMarketValueUpdate",
	"StuckCancel",
	"DungonEscapeReady",
	"FactionWarfareClusterState",
	"FactionWarfareHasUnclaimedWeeklyReportsEvent",
	"SimpleFeedback",
	"SmartClusterQueueSkipClusterError",
	"XignCodeEvent",
	"BatchUseItemStart",
	"BatchUseItemEnd",
	"RedZonePlayerNotification",
	"RedZoneEventCheatCleanup",
	"RedZoneFortressEventChestOpened",
	"RedZoneWorldEvent",
	"FactionWarfareStats",
	"UpdateFactionBalanceFactors",
	"FactionEnlistmentChanged",
	"UpdateFactionRank",
	"FactionWarfareCampaignRewardsUnlocked",
	"FeaturedFeatureUpdate",
	"NewPowerCrystalObject",
	"MinimapCrystalPositionMarker",
	"CarryPowerCrystalUpdate",
	"PickupPowerCrystalStart",
	"PickupPowerCrystalCancel",
	"PickupPowerCrystalFinished",
	"DoSimpleActionStart",
	"DoSimpleActionCancel",
	"DoSimpleActionFinished",
	"NotifyGuestAccountVerified",
	"MightAndFavorReceivedEvent",
	"WeeklyPvpChallengeRewardStateUpdate",
	"NewUnlockedPvpSeasonChallengeRewards",
	"StaticDungeonEntrancesDungeonEventStatusUpdates",
	"StaticDungeonDungeonValueUpdate",
	"StaticDungeonEntranceDungeonEventsAborted",
	"InAppPurchaseConfirmedGooglePlay",
	"FeatureSwitchInfo",
	"PartyJoinRequestAborted",
	"PartyInviteAborted",
	"PartyStartHuntRequest",
	"PartyStartHuntRequested",
	"PartyStartHuntRequestAnswer",
	"PartyPlayerLeaveScheduled",
	"GuildInviteDeclined",
	"CancelMultiSpellSlots",
	"NewVisualEventObject",
	"CastleClaimProgress",
	"CastleClaimProgressLogo",
	"TownPortalUpdateState",
	"TownPortalFailed",
	"ConsumableVanityChargesAdded",
	"FestivitiesUpdate",
	"NewBannerObject",
	"NewMistsImmediateReturnExit",
	"MistsPlayerJoinedInfo",
	"NewMistsStaticEntrance",
	"NewMistsOpenWorldExit",
	"NewTunnelExitTemp",
	"NewMistsWispSpawn",
	"MistsWispSpawnStateChange",
	"NewMistsCityEntrance",
	"NewMistsCityRoadsEntrance",
	"MistsCityRoadsEntrancePartyStateUpdate",
	"MistsCityRoadsEntranceClearStateForParty",
	"MistsEntranceDataChanged",
	"NewCagedObject",
	"CagedObjectStateUpdated",
	"EntrancePartyBindingCreated",
	"EntrancePartyBindingCleared",
	"EntrancePartyBindingInfos",
	"NewMistsBorderExit",
	"NewMistsDungeonExit",
	"LocalQuestInfos",
	"LocalQuestStarted",
	"LocalQuestActive",
	"LocalQuestInactive",
	"LocalQuestProgressUpdate",
	"NewUnrestrictedPvpZone",
	"TemporaryFlaggingStatusUpdate",
	"SpellTestPerformanceUpdate",
	"Transformation",
	"TransformationEnd",
	"UpdateTrustlevel",
	"RevealHiddenTimeStamps",
	"ModifyItemTraitFinished",
	"RerollItemTraitValueFinished",
	"HuntQuestProgressInfo",
	"HuntStarted",
	"HuntFinished",
	"HuntAborted",
	"HuntMissionStepStateUpdate",
	"NewHuntTrack",
	"HuntMissionUpdate",
	"HuntQuestMissionProgressUpdate",
	"HuntTrackUsed",
	"HuntTrackUseableAgain",
	"MinimapHuntTrackMarkers",
	"NoTracksFound",
	"HuntQuestAborted",
	"InteractWithTrackStart",
	"InteractWithTrackCancel",
	"InteractWithTrackFinished",
	"NewDynamicCompound",
	"LegendaryItemDestroyed",
	"AttunementInfo",
	"TerritoryClaimRaidedRawEnergyCrystalResult",
	"CarriedObjectExpiryWarning",
	"CarriedObjectExpired",
	"TerritoryRaidStart",
	"TerritoryRaidCancel",
	"TerritoryRaidFinished",
	"TerritoryRaidResult",
	"TerritoryMonolithActiveRaidStatus",
	"TerritoryMonolithActiveRaidCancelled",
	"MonolithEnergyStorageUpdate",
	"MonolithNextScheduledOpenWorldAttackUpdate",
	"MonolithProtectedBuildingsDamageReductionUpdate",
	"NewBuildingBaseEvent",
	"NewFortificationBuilding",
	"NewCastleGateBuilding",
	"BuildingDurabilityUpdate",
	"MonolithFortificationPointsUpdate",
	"FortificationBuildingUpgradeInfo",
	"FortificationBuildingsDamageStateUpdate",
	"SiegeNotificationEvent",
	"UpdateEnemyWarBannerActive",
	"TerritoryAnnouncePlayerEjection",
	"CastleGateSwitchUseStarted",
	"CastleGateSwitchUseFinished",
	"FortificationBuildingWillDowngrade",
	"BotCommand",
	"JournalAchievementProgressUpdate",
	"JournalClaimableRewardUpdate",
	"KeySync",
	"LocalQuestAreaGone",
	"DynamicTemplate",
	"DynamicTemplateForcedStateChange",
	"NewOutlandsTeleportationPortal",
	"NewOutlandsTeleportationReturnPortal",
	"OutlandsTeleportationBindingCleared",
	"OutlandsTeleportationReturnPortalUpdateEvent",
	"PlayerUsedOutlandsTeleportationPortal",
	"EncumberedRestricted",
	"NewPiledObject",
	"PiledObjectStateChanged",
	"NewSmugglerCrateDeliveryStation",
	"KillRewardedNoFame",
	"PickupFromPiledObjectStart",
	"PickupFromPiledObjectCancel",
	"PickupFromPiledObjectReset",
	"PickupFromPiledObjectFinished",
	"ArmoryActivityChange",
	"NewKillTrophyFurnitureBuilding",
	"HellDungeonsPlayerJoinedInfo",
	"NewTileSwitchTrigger",
	"NewMultiRewardObject",
	"NewHellDungeonSoulShrineObject",
	"HellDungeonSoulShrineStateUpdate",
	"NewResurrectionShrine",
	"UpdateResurrectionShrine",
	"StandTimeFinished",
	"EpicAchievementAndStatsUpdate",
	"SpectateTargetAfterDeathUpdate",
	"SpectateTargetAfterDeathEnded",
	"NewHellDungeonUpwardExit",
	"NewHellDungeonSoulExit",
	"NewHellDungeonDownwardExit",
	"NewHellDungeonChestExit",
	"NewCorruptedStaticEntrance",
	"NewHellDungeonStaticEntrance",
	"UpdateHellDungeonStaticEntranceState",
	"DebugTriggerHellDungeonShutdownStart",
	"FullJournalQuestInfo",
	"JournalQuestProgressInfo",
	"NewHellDungeonRoomShrineObject",
	"HellDungeonRoomShrineStateUpdate",
	"SimpleBehaviourBuildingStateUpdate",
	"SetTimeScaling",
	"StopTimeScaling",
	"KeyValidation",
	"PlayerJoinMapMarkerTimerStates",
	"NewMapMarkerTimer",
	"RemoveMapMarkerTimer",
	"NewFactionFortressObject",
	"FactionFortressAnnouncePlayerEjection",
	"RewardFactionWarfareSupply",
	"FactionCaptureAreaProgressUpdate",
	"FactionFortressClaimed",
	"FactionFortressWeaponCachesSpawned",
	"FactionFortressWeaponCacheClaimed",
	"FactionFortressFightStateUpdate",
	"FactionFortressCutoffFightStateUpdate",
	"FactionFortressFightEnded",
	"NewFactionWarfarePortal",
	"FactionPortalTargetUpdate",
	"FactionFortressFightStartedInRemoteClusterEvent",
	"FactionFortressFightFinishedInRemoteClusterEvent",
	"FactionDuchySupplyWarDefensiveVictoryEvent",
	"FactionDuchyReconnectedFromCutoffEvent",
	"FactionFortressCutoffFightCancelledByClusterOwnerChangeEvent",
	"FactionDuchyEnteredCutoffStateEvent",
	"LeaveProtectionStateUpdate",
	"RedZoneEventStandings",
	"NewFactionBattleStandardDeliveryStation",
	"NewLoreSnippetObject",
	"LoreSnippetObjectStateUpdate",
	"LoreSnippedClaimed",
	"LoreSnippetStatesChangedByCheat",
	"NewTeleporterNode",
	"TeleporterNodeStateChanged",
	"TeleporterConnectionsFullStateUpdate",
	"TeleporterConnectionStateChanged",
	"RetrieveCarriableObjectStart",
	"RetrieveCarriableObjectCancel",
	"RetrieveCarriableObjectReset",
	"RetrieveCarriableObjectFinished",
	"LosingCarriableObjectStart",
	"LosingCarriableObjectFinished",
}
