package gamecodes

// Code generated from src/StatisticsAnalysisTool/Network/OperationCodes.cs. DO NOT EDIT.

type Op int

const (
	OpUnused Op = iota
	OpPing
	OpJoin
	OpVersionedOperation
	OpCreateAccount
	OpLogin
	OpCreateGuestAccount
	OpCreatePlatformOnlyAccount
	OpSendCrashLog
	OpSendTraceRoute
	OpSendVfxStats
	OpSendGamePingInfo
	OpCreateCharacter
	OpDeleteCharacter
	OpSelectCharacter
	OpAcceptPopups
	OpRedeemKeycode
	OpGetGameServerByCluster
	OpGetShopPurchaseUrl
	OpGetReferralSeasonDetails
	OpGetReferralLink
	OpGetShopTilesForCategory
	OpMove
	OpAttackStart
	OpCastStart
	OpCastCancel
	OpTerminateToggleSpell
	OpChannelingCancel
	OpAttackBuildingStart
	OpInventoryDestroyItem
	OpInventoryMoveItem
	OpInventoryRecoverItem
	OpInventoryRecoverAllItems
	OpInventorySplitStack
	OpInventorySplitStackInto
	OpInventoryStack
	OpInventoryReorder
	OpInventoryDropAll
	OpInventoryAddToStacks
	OpInventoryMoveGivenItems
	OpGetClusterData
	OpChangeCluster
	OpConsoleCommand
	OpChatMessage
	OpReportClientError
	OpRegisterToObject
	OpUnRegisterFromObject
	OpCraftBuildingChangeSettings
	OpCraftBuildingTakeMoney
	OpRepairBuildingChangeSettings
	OpRepairBuildingTakeMoney
	OpActionBuildingChangeSettings
	OpHarvestStart
	OpHarvestCancel
	OpTakeSilver
	OpActionOnBuildingStart
	OpActionOnBuildingCancel
	OpInstallResourceStart
	OpInstallResourceCancel
	OpInstallSilver
	OpBuildingFillNutrition
	OpBuildingChangeRenovationState
	OpBuildingBuySkin
	OpBuildingClaim
	OpBuildingGiveup
	OpBuildingNutritionSilverStorageDeposit
	OpBuildingNutritionSilverStorageWithdraw
	OpBuildingNutritionSilverRewardSet
	OpConstructionSiteCreate
	OpPlaceableObjectPlace
	OpPlaceableObjectPlaceCancel
	OpPlaceableObjectPickup
	OpFurnitureObjectUse
	OpFarmableHarvest
	OpFarmableFinishGrownItem
	OpFarmableDestroy
	OpFarmableGetProduct
	OpFarmableFill
	OpTearDownConstructionSite
	OpAuctionCreateOffer
	OpAuctionCreateRequest
	OpAuctionGetOffers
	OpAuctionGetRequests
	OpAuctionBuyOffer
	OpAuctionAbortAuction
	OpAuctionModifyAuction
	OpAuctionAbortOffer
	OpAuctionAbortRequest
	OpAuctionSellRequest
	OpAuctionGetFinishedAuctions
	OpAuctionGetFinishedAuctionsCount
	OpAuctionFetchAuction
	OpAuctionGetMyOpenOffers
	OpAuctionGetMyOpenRequests
	OpAuctionGetMyOpenAuctions
	OpAuctionGetItemAverageStats
	OpAuctionGetItemAverageValue
	OpAuctionGetLowestOfferPrices
	OpContainerOpen
	OpContainerClose
	OpContainerManageSubContainer
	OpRespawn
	OpSuicide
	OpJoinGuild
	OpLeaveGuild
	OpCreateGuild
	OpInviteToGuild
	OpDeclineGuildInvitation
	OpKickFromGuild
	OpInstantJoinGuild
	OpDuellingChallengePlayer
	OpDuellingAcceptChallenge
	OpDuellingDenyChallenge
	OpChangeClusterTax
	OpClaimTerritory
	OpGiveUpTerritory
	OpChangeTerritoryAccessRights
	OpGetMonolithInfo
	OpGetClaimInfo
	OpGetAttackInfo
	OpGetTerritorySeasonPoints
	OpGetAttackSchedule
	OpGetMatches
	OpGetMatchDetails
	OpJoinMatch
	OpLeaveMatch
	OpGetClusterInstanceInfoForStaticCluster
	OpChangeChatSettings
	OpLogoutStart
	OpLogoutCancel
	OpClaimOrbStart
	OpClaimOrbCancel
	OpMatchLootChestOpeningStart
	OpMatchLootChestOpeningCancel
	OpDepositToGuildAccount
	OpWithdrawalFromAccount
	OpChangeGuildPayUpkeepFlag
	OpChangeGuildTax
	OpGetMyTerritories
	OpMorganaCommand
	OpGetServerInfo
	OpSubscribeToCluster
	OpAnswerMercenaryInvitation
	OpGetCharacterEquipment
	OpGetCharacterSteamAchievements
	OpGetCharacterStats
	OpGetKillHistoryDetails
	OpReSpecAchievement
	OpChangeAvatar
	OpGetRankings
	OpGetRank
	OpGetGvgSeasonRankings
	OpGetGvgSeasonRank
	OpGetGvgSeasonHistoryRankings
	OpGetGvgSeasonGuildMemberHistory
	OpKickFromGvGMatch
	OpGetCrystalLeagueDailySeasonPoints
	OpGetChestLogs
	OpGetAccessRightLogs
	OpGetGuildAccountLogs
	OpGetGuildAccountLogsLargeAmount
	OpInviteToPlayerTrade
	OpPlayerTradeCancel
	OpPlayerTradeInvitationAccept
	OpPlayerTradeAddItem
	OpPlayerTradeRemoveItem
	OpPlayerTradeAcceptTrade
	OpPlayerTradeSetSilverOrGold
	OpSendMiniMapPing
	OpStuck
	OpBuyRealEstate
	OpClaimRealEstate
	OpGiveUpRealEstate
	OpChangeRealEstateOutline
	OpGetMailInfos
	OpGetMailCount
	OpReadMail
	OpSendNewMail
	OpDeleteMail
	OpMarkMailUnread
	OpClaimAttachmentFromMail
	OpApplyToGuild
	OpAnswerGuildApplication
	OpRequestGuildFinderFilteredList
	OpUpdateGuildRecruitmentInfo
	OpRequestGuildRecruitmentInfo
	OpRequestGuildFinderNameSearch
	OpRequestGuildFinderRecommendedList
	OpRegisterChatPeer
	OpSendChatMessage
	OpSendModeratorMessage
	OpJoinChatChannel
	OpLeaveChatChannel
	OpSendWhisperMessage
	OpSay
	OpPlayEmote
	OpStopEmote
	OpGetClusterMapInfo
	OpAccessRightsChangeSettings
	OpMount
	OpMountCancel
	OpBuyJourney
	OpSetSaleStatusForEstate
	OpResolveGuildOrPlayerName
	OpGetRespawnInfos
	OpMakeHome
	OpLeaveHome
	OpResurrectionReply
	OpAllianceCreate
	OpAllianceDisband
	OpAllianceGetMemberInfos
	OpAllianceInvite
	OpAllianceAnswerInvitation
	OpAllianceCancelInvitation
	OpAllianceKickGuild
	OpAllianceLeave
	OpAllianceChangeGoldPaymentFlag
	OpAllianceGetDetailInfo
	OpGetIslandInfos
	OpBuyMyIsland
	OpBuyGuildIsland
	OpUpgradeMyIsland
	OpUpgradeGuildIsland
	OpTerritoryFillNutrition
	OpTeleportBack
	OpPartyInvitePlayer
	OpPartyRequestJoin
	OpPartyAnswerInvitation
	OpPartyAnswerJoinRequest
	OpPartyLeave
	OpPartyKickPlayer
	OpPartyMakeLeader
	OpPartyChangeLootSetting
	OpPartyMarkObject
	OpPartySetRole
	OpPartyChangeFactionWarfareRequestReinforcementsSetting
	OpSetGuildCodex
	OpExitEnterStart
	OpExitEnterCancel
	OpQuestGiverRequest
	OpGoldMarketGetBuyOffer
	OpGoldMarketGetBuyOfferFromSilver
	OpGoldMarketGetSellOffer
	OpGoldMarketGetSellOfferFromSilver
	OpGoldMarketBuyGold
	OpGoldMarketSellGold
	OpGoldMarketCreateSellOrder
	OpGoldMarketCreateBuyOrder
	OpGoldMarketGetInfos
	OpGoldMarketCancelOrder
	OpGoldMarketGetAverageInfo
	OpTreasureChestUsingStart
	OpTreasureChestUsingCancel
	OpUseLootChest
	OpUseShrine
	OpUseHellgateShrine
	OpGetSiegeBannerInfo
	OpLaborerStartJob
	OpLaborerTakeJobLoot
	OpLaborerDismiss
	OpLaborerMove
	OpLaborerBuyItem
	OpLaborerUpgrade
	OpBuyPremium
	OpRealEstateGetAuctionData
	OpRealEstateBidOnAuction
	OpFriendInvite
	OpFriendAnswerInvitation
	OpFriendCancelnvitation
	OpFriendRemove
	OpEquipmentItemChangeSpell
	OpExpeditionRegister
	OpExpeditionRegisterCancel
	OpJoinExpedition
	OpDeclineExpeditionInvitation
	OpVoteStart
	OpVoteDoVote
	OpRatingDoRate
	OpEnteringExpeditionStart
	OpEnteringExpeditionCancel
	OpActivateExpeditionCheckPoint
	OpArenaRegister
	OpArenaAddInvite
	OpArenaRegisterCancel
	OpArenaLeave
	OpJoinArenaMatch
	OpDeclineArenaInvitation
	OpEnteringArenaStart
	OpEnteringArenaCancel
	OpArenaCustomMatch
	OpUpdateCharacterStatement
	OpBoostFarmable
	OpGetStrikeHistory
	OpUseFunction
	OpUsePortalEntrance
	OpResetPortalBinding
	OpQueryPortalBinding
	OpClaimPaymentTransaction
	OpChangeUseFlag
	OpClientPerformanceStats
	OpExtendedHardwareStats
	OpClientLowMemoryWarning
	OpTerritoryClaimStart
	OpTerritoryClaimCancel
	OpDeliverCarriableObjectStart
	OpDeliverCarriableObjectCancel
	OpTerritoryUpgradeWithPowerCrystal
	OpRequestAppStoreProducts
	OpVerifyProductPurchase
	OpQueryGuildPlayerStats
	OpQueryAllianceGuildStats
	OpTrackAchievements
	OpSetAchievementsAutoLearn
	OpDepositItemToGuildCurrency
	OpWithdrawalItemFromGuildCurrency
	OpAuctionSellSpecificItemRequest
	OpFishingStart
	OpFishingCasting
	OpFishingCast
	OpFishingCatch
	OpFishingPull
	OpFishingGiveLine
	OpFishingFinish
	OpFishingCancel
	OpCreateGuildAccessTag
	OpDeleteGuildAccessTag
	OpRenameGuildAccessTag
	OpFlagGuildAccessTagGuildPermission
	OpAssignGuildAccessTag
	OpRemoveGuildAccessTagFromPlayer
	OpModifyGuildAccessTagEditors
	OpRequestPublicAccessTags
	OpChangeAccessTagPublicFlag
	OpUpdateGuildAccessTag
	OpSteamStartMicrotransaction
	OpSteamFinishMicrotransaction
	OpRequestXboxPurchaseIntent
	OpCloseXboxPurchaseIntent
	OpSteamIdHasActiveAccount
	OpCheckEmailAccountState
	OpLinkAccountToSteamId
	OpEpicIdHasActiveAccount
	OpLinkAccountToEpicId
	OpXboxIdHasActiveAccount
	OpInAppConfirmPaymentGooglePlay
	OpInAppConfirmPaymentAppleAppStore
	OpInAppPurchaseRequest
	OpInAppPurchaseFailed
	OpCharacterSubscriptionInfo
	OpAccountSubscriptionInfo
	OpBuyGvgSeasonBooster
	OpChangeFlaggingPrepare
	OpOverCharge
	OpOverChargeEnd
	OpRequestTrusted
	OpChangeGuildLogo
	OpPartyFinderRegisterForUpdates
	OpPartyFinderUnregisterForUpdates
	OpPartyFinderEnlistNewPartySearch
	OpPartyFinderDeletePartySearch
	OpPartyFinderChangePartySearch
	OpPartyFinderChangeRole
	OpPartyFinderApplyForGroup
	OpPartyFinderAcceptOrDeclineApplyForGroup
	OpPartyFinderGetEquipmentSnapshot
	OpPartyFinderRegisterApplicants
	OpPartyFinderUnregisterApplicants
	OpPartyFinderFulltextSearch
	OpPartyFinderRequestEquipmentSnapshot
	OpGetPersonalSeasonTrackerData
	OpGetPersonalSeasonPastRewardData
	OpUseConsumableFromInventory
	OpClaimPersonalSeasonReward
	OpXignCodeMessageToServer
	OpBattlEyeMessageToServer
	OpSetNextTutorialState
	OpAddPlayerToMuteList
	OpRemovePlayerFromMuteList
	OpProductShopUserEvent
	OpGetVanityUnlocks
	OpBuyVanityUnlocks
	OpGetMountSkins
	OpSetMountSkin
	OpSetWardrobe
	OpChangeCustomization
	OpChangePlayerIslandData
	OpGetGuildChallengePoints
	OpSmartQueueJoin
	OpSmartQueueLeave
	OpSmartQueueSelectSpawnCluster
	OpUpgradeHideout
	OpInitHideoutAttackStart
	OpInitHideoutAttackCancel
	OpHideoutFillNutrition
	OpHideoutGetInfo
	OpHideoutGetOwnerInfo
	OpHideoutSetTribute
	OpHideoutUpgradeWithPowerCrystal
	OpHideoutDeclareHQ
	OpHideoutUndeclareHQ
	OpHideoutGetHQRequirements
	OpHideoutBoost
	OpHideoutBoostConstruction
	OpOpenWorldAttackScheduleStart
	OpOpenWorldAttackScheduleCancel
	OpOpenWorldAttackConquerStart
	OpOpenWorldAttackConquerCancel
	OpGetOpenWorldAttackDetails
	OpGetNextOpenWorldAttackScheduleTime
	OpRecoverVaultFromHideout
	OpGetGuildEnergyDrainInfo
	OpChannelingUpdate
	OpUseCorruptedShrine
	OpRequestEstimatedMarketValue
	OpLogFeedback
	OpGetInfamyInfo
	OpGetPartySmartClusterQueuePriority
	OpSetPartySmartClusterQueuePriority
	OpClientAntiAutoClickerInfo
	OpClientBotPatternDetectionInfo
	OpClientAntiGatherClickerInfo
	OpLoadoutCreate
	OpLoadoutRead
	OpLoadoutReadHeaders
	OpLoadoutUpdate
	OpLoadoutDelete
	OpLoadoutOrderUpdate
	OpLoadoutEquip
	OpBatchUseItemCancel
	OpEnlistFactionWarfare
	OpGetFactionWarfareWeeklyReport
	OpClaimFactionWarfareWeeklyReport
	OpGetFactionWarfareCampaignData
	OpClaimFactionWarfareItemReward
	OpSendMemoryConsumption
	OpPickupCarriableObjectStart
	OpPickupCarriableObjectCancel
	OpSetSavingChestLogsFlag
	OpGetSavingChestLogsFlag
	OpRegisterGuestAccount
	OpResendGuestAccountVerificationEmail
	OpDoSimpleActionStart
	OpDoSimpleActionCancel
	OpGetGvgSeasonContributionByActivity
	OpGetGvgSeasonContributionByCrystalLeague
	OpGetGuildMightCategoryContribution
	OpGetGuildMightCategoryOverview
	OpGetPvpChallengeData
	OpClaimPvpChallengeWeeklyReward
	OpGetPersonalMightStats
	OpGetPvpChallengeSeasonRewards
	OpGetPvpChallengeSeasonRewardItems
	OpClaimPvpChallengeSeasonRewards
	OpClaimPvpChallengeSeasonRewardItems
	OpAuctionGetLoadoutOffers
	OpAuctionBuyLoadoutOffer
	OpAccountDeletionRequest
	OpAccountReactivationRequest
	OpCreateModeratorNotesForAccount
	OpGetModeratorNotesForAccount
	OpGetModerationEscalationDefiniton
	OpEventBasedPopupAddSeen
	OpGetItemKillHistory
	OpGetVanityConsumables
	OpEquipKillEmote
	OpChangeKillEmotePlayOnKnockdownSetting
	OpBuyVanityConsumableCharges
	OpReclaimVanityItem
	OpGetArenaRankings
	OpGetCrystalLeagueStatistics
	OpSendOptionsLog
	OpSendControlsOptionsLog
	OpMistsUseImmediateReturnExit
	OpMistsUseStaticEntrance
	OpMistsUseCityRoadsEntrance
	OpChangeNewGuildMemberMail
	OpGetNewGuildMemberMail
	OpChangeGuildFactionAllegiance
	OpGetGuildFactionAllegiance
	OpGuildBannerChange
	OpGuildGetOptionalStats
	OpGuildSetOptionalStats
	OpGetPlayerInfoForStalk
	OpPayGoldForCharacterTypeChange
	OpQuickSellAuctionQueryAction
	OpQuickSellAuctionSellAction
	OpFcmTokenToServer
	OpApnsTokenToServer
	OpDeathRecap
	OpAuctionFetchFinishedAuctions
	OpAbortAuctionFetchFinishedAuctions
	OpRequestLegendaryEvenHistory
	OpPartyAnswerStartHuntRequest
	OpHuntAbort
	OpUseFindTrackSpellFromItemPrepare
	OpInteractWithTrackStart
	OpInteractWithTrackCancel
	OpTerritoryRaidStart
	OpTerritoryRaidCancel
	OpTerritoryClaimRaidedRawEnergyCrystalResult
	OpGvGSeasonPlayerGuildParticipationDetails
	OpDailyMightBonus
	OpClaimDailyMightBonus
	OpGetFortificationGroupInfo
	OpUpgradeFortificationGroup
	OpCancelUpgradeFortificationGroup
	OpDowngradeFortificationGroup
	OpGetClusterActivityChestEstimates
	OpPartyReadyCheckBegin
	OpPartyReadyCheckUpdate
	OpClaimAlbionJournalReward
	OpTrackAlbionJournalAchievements
	OpTrackAlbionJournalAchievementSubCategory
	OpRequestOutlandsTeleportationUsage
	OpPickupFromPiledObjectStart
	OpPickupFromPiledObjectCancel
	OpAssetOverview
	OpAssetOverviewTabs
	OpAssetOverviewTabContent
	OpAssetOverviewUnfreezeCache
	OpAssetOverviewSearch
	OpAssetOverviewSearchTabs
	OpAssetOverviewSearchTabContent
	OpAssetOverviewRecoverPlayerVault
	OpImmortalizeKillTrophy
	OpArmorySearch
	OpArmoryItemUsageStatistics
	OpArmoryActivityUsageStatistics
	OpHellDungeonUseStaticEntrance
	OpTravelIslandShowroom
	OpGetXuids
	OpXboxServiceTicket
	OpEvaluatePlatformPerks
	OpLinkAccountToXbox
	OpTravelFactionWarfarePortal
	OpRequestRedZoneEventStandings
	OpGetZergDebuffInfo
	OpRequestLoreSnippetStates
	OpRetrieveCarriableObjectStart
	OpRetrieveCarriableObjectCancel
)

// OpName returns the C# identifier for a code, or empty if unknown.
func OpName(c Op) string {
	if c < 0 || int(c) >= len(OpNames) { return "" }
	return OpNames[c]
}

var OpNames = [...]string{
	"Unused",
	"Ping",
	"Join",
	"VersionedOperation",
	"CreateAccount",
	"Login",
	"CreateGuestAccount",
	"CreatePlatformOnlyAccount",
	"SendCrashLog",
	"SendTraceRoute",
	"SendVfxStats",
	"SendGamePingInfo",
	"CreateCharacter",
	"DeleteCharacter",
	"SelectCharacter",
	"AcceptPopups",
	"RedeemKeycode",
	"GetGameServerByCluster",
	"GetShopPurchaseUrl",
	"GetReferralSeasonDetails",
	"GetReferralLink",
	"GetShopTilesForCategory",
	"Move",
	"AttackStart",
	"CastStart",
	"CastCancel",
	"TerminateToggleSpell",
	"ChannelingCancel",
	"AttackBuildingStart",
	"InventoryDestroyItem",
	"InventoryMoveItem",
	"InventoryRecoverItem",
	"InventoryRecoverAllItems",
	"InventorySplitStack",
	"InventorySplitStackInto",
	"InventoryStack",
	"InventoryReorder",
	"InventoryDropAll",
	"InventoryAddToStacks",
	"InventoryMoveGivenItems",
	"GetClusterData",
	"ChangeCluster",
	"ConsoleCommand",
	"ChatMessage",
	"ReportClientError",
	"RegisterToObject",
	"UnRegisterFromObject",
	"CraftBuildingChangeSettings",
	"CraftBuildingTakeMoney",
	"RepairBuildingChangeSettings",
	"RepairBuildingTakeMoney",
	"ActionBuildingChangeSettings",
	"HarvestStart",
	"HarvestCancel",
	"TakeSilver",
	"ActionOnBuildingStart",
	"ActionOnBuildingCancel",
	"InstallResourceStart",
	"InstallResourceCancel",
	"InstallSilver",
	"BuildingFillNutrition",
	"BuildingChangeRenovationState",
	"BuildingBuySkin",
	"BuildingClaim",
	"BuildingGiveup",
	"BuildingNutritionSilverStorageDeposit",
	"BuildingNutritionSilverStorageWithdraw",
	"BuildingNutritionSilverRewardSet",
	"ConstructionSiteCreate",
	"PlaceableObjectPlace",
	"PlaceableObjectPlaceCancel",
	"PlaceableObjectPickup",
	"FurnitureObjectUse",
	"FarmableHarvest",
	"FarmableFinishGrownItem",
	"FarmableDestroy",
	"FarmableGetProduct",
	"FarmableFill",
	"TearDownConstructionSite",
	"AuctionCreateOffer",
	"AuctionCreateRequest",
	"AuctionGetOffers",
	"AuctionGetRequests",
	"AuctionBuyOffer",
	"AuctionAbortAuction",
	"AuctionModifyAuction",
	"AuctionAbortOffer",
	"AuctionAbortRequest",
	"AuctionSellRequest",
	"AuctionGetFinishedAuctions",
	"AuctionGetFinishedAuctionsCount",
	"AuctionFetchAuction",
	"AuctionGetMyOpenOffers",
	"AuctionGetMyOpenRequests",
	"AuctionGetMyOpenAuctions",
	"AuctionGetItemAverageStats",
	"AuctionGetItemAverageValue",
	"AuctionGetLowestOfferPrices",
	"ContainerOpen",
	"ContainerClose",
	"ContainerManageSubContainer",
	"Respawn",
	"Suicide",
	"JoinGuild",
	"LeaveGuild",
	"CreateGuild",
	"InviteToGuild",
	"DeclineGuildInvitation",
	"KickFromGuild",
	"InstantJoinGuild",
	"DuellingChallengePlayer",
	"DuellingAcceptChallenge",
	"DuellingDenyChallenge",
	"ChangeClusterTax",
	"ClaimTerritory",
	"GiveUpTerritory",
	"ChangeTerritoryAccessRights",
	"GetMonolithInfo",
	"GetClaimInfo",
	"GetAttackInfo",
	"GetTerritorySeasonPoints",
	"GetAttackSchedule",
	"GetMatches",
	"GetMatchDetails",
	"JoinMatch",
	"LeaveMatch",
	"GetClusterInstanceInfoForStaticCluster",
	"ChangeChatSettings",
	"LogoutStart",
	"LogoutCancel",
	"ClaimOrbStart",
	"ClaimOrbCancel",
	"MatchLootChestOpeningStart",
	"MatchLootChestOpeningCancel",
	"DepositToGuildAccount",
	"WithdrawalFromAccount",
	"ChangeGuildPayUpkeepFlag",
	"ChangeGuildTax",
	"GetMyTerritories",
	"MorganaCommand",
	"GetServerInfo",
	"SubscribeToCluster",
	"AnswerMercenaryInvitation",
	"GetCharacterEquipment",
	"GetCharacterSteamAchievements",
	"GetCharacterStats",
	"GetKillHistoryDetails",
	"ReSpecAchievement",
	"ChangeAvatar",
	"GetRankings",
	"GetRank",
	"GetGvgSeasonRankings",
	"GetGvgSeasonRank",
	"GetGvgSeasonHistoryRankings",
	"GetGvgSeasonGuildMemberHistory",
	"KickFromGvGMatch",
	"GetCrystalLeagueDailySeasonPoints",
	"GetChestLogs",
	"GetAccessRightLogs",
	"GetGuildAccountLogs",
	"GetGuildAccountLogsLargeAmount",
	"InviteToPlayerTrade",
	"PlayerTradeCancel",
	"PlayerTradeInvitationAccept",
	"PlayerTradeAddItem",
	"PlayerTradeRemoveItem",
	"PlayerTradeAcceptTrade",
	"PlayerTradeSetSilverOrGold",
	"SendMiniMapPing",
	"Stuck",
	"BuyRealEstate",
	"ClaimRealEstate",
	"GiveUpRealEstate",
	"ChangeRealEstateOutline",
	"GetMailInfos",
	"GetMailCount",
	"ReadMail",
	"SendNewMail",
	"DeleteMail",
	"MarkMailUnread",
	"ClaimAttachmentFromMail",
	"ApplyToGuild",
	"AnswerGuildApplication",
	"RequestGuildFinderFilteredList",
	"UpdateGuildRecruitmentInfo",
	"RequestGuildRecruitmentInfo",
	"RequestGuildFinderNameSearch",
	"RequestGuildFinderRecommendedList",
	"RegisterChatPeer",
	"SendChatMessage",
	"SendModeratorMessage",
	"JoinChatChannel",
	"LeaveChatChannel",
	"SendWhisperMessage",
	"Say",
	"PlayEmote",
	"StopEmote",
	"GetClusterMapInfo",
	"AccessRightsChangeSettings",
	"Mount",
	"MountCancel",
	"BuyJourney",
	"SetSaleStatusForEstate",
	"ResolveGuildOrPlayerName",
	"GetRespawnInfos",
	"MakeHome",
	"LeaveHome",
	"ResurrectionReply",
	"AllianceCreate",
	"AllianceDisband",
	"AllianceGetMemberInfos",
	"AllianceInvite",
	"AllianceAnswerInvitation",
	"AllianceCancelInvitation",
	"AllianceKickGuild",
	"AllianceLeave",
	"AllianceChangeGoldPaymentFlag",
	"AllianceGetDetailInfo",
	"GetIslandInfos",
	"BuyMyIsland",
	"BuyGuildIsland",
	"UpgradeMyIsland",
	"UpgradeGuildIsland",
	"TerritoryFillNutrition",
	"TeleportBack",
	"PartyInvitePlayer",
	"PartyRequestJoin",
	"PartyAnswerInvitation",
	"PartyAnswerJoinRequest",
	"PartyLeave",
	"PartyKickPlayer",
	"PartyMakeLeader",
	"PartyChangeLootSetting",
	"PartyMarkObject",
	"PartySetRole",
	"PartyChangeFactionWarfareRequestReinforcementsSetting",
	"SetGuildCodex",
	"ExitEnterStart",
	"ExitEnterCancel",
	"QuestGiverRequest",
	"GoldMarketGetBuyOffer",
	"GoldMarketGetBuyOfferFromSilver",
	"GoldMarketGetSellOffer",
	"GoldMarketGetSellOfferFromSilver",
	"GoldMarketBuyGold",
	"GoldMarketSellGold",
	"GoldMarketCreateSellOrder",
	"GoldMarketCreateBuyOrder",
	"GoldMarketGetInfos",
	"GoldMarketCancelOrder",
	"GoldMarketGetAverageInfo",
	"TreasureChestUsingStart",
	"TreasureChestUsingCancel",
	"UseLootChest",
	"UseShrine",
	"UseHellgateShrine",
	"GetSiegeBannerInfo",
	"LaborerStartJob",
	"LaborerTakeJobLoot",
	"LaborerDismiss",
	"LaborerMove",
	"LaborerBuyItem",
	"LaborerUpgrade",
	"BuyPremium",
	"RealEstateGetAuctionData",
	"RealEstateBidOnAuction",
	"FriendInvite",
	"FriendAnswerInvitation",
	"FriendCancelnvitation",
	"FriendRemove",
	"EquipmentItemChangeSpell",
	"ExpeditionRegister",
	"ExpeditionRegisterCancel",
	"JoinExpedition",
	"DeclineExpeditionInvitation",
	"VoteStart",
	"VoteDoVote",
	"RatingDoRate",
	"EnteringExpeditionStart",
	"EnteringExpeditionCancel",
	"ActivateExpeditionCheckPoint",
	"ArenaRegister",
	"ArenaAddInvite",
	"ArenaRegisterCancel",
	"ArenaLeave",
	"JoinArenaMatch",
	"DeclineArenaInvitation",
	"EnteringArenaStart",
	"EnteringArenaCancel",
	"ArenaCustomMatch",
	"UpdateCharacterStatement",
	"BoostFarmable",
	"GetStrikeHistory",
	"UseFunction",
	"UsePortalEntrance",
	"ResetPortalBinding",
	"QueryPortalBinding",
	"ClaimPaymentTransaction",
	"ChangeUseFlag",
	"ClientPerformanceStats",
	"ExtendedHardwareStats",
	"ClientLowMemoryWarning",
	"TerritoryClaimStart",
	"TerritoryClaimCancel",
	"DeliverCarriableObjectStart",
	"DeliverCarriableObjectCancel",
	"TerritoryUpgradeWithPowerCrystal",
	"RequestAppStoreProducts",
	"VerifyProductPurchase",
	"QueryGuildPlayerStats",
	"QueryAllianceGuildStats",
	"TrackAchievements",
	"SetAchievementsAutoLearn",
	"DepositItemToGuildCurrency",
	"WithdrawalItemFromGuildCurrency",
	"AuctionSellSpecificItemRequest",
	"FishingStart",
	"FishingCasting",
	"FishingCast",
	"FishingCatch",
	"FishingPull",
	"FishingGiveLine",
	"FishingFinish",
	"FishingCancel",
	"CreateGuildAccessTag",
	"DeleteGuildAccessTag",
	"RenameGuildAccessTag",
	"FlagGuildAccessTagGuildPermission",
	"AssignGuildAccessTag",
	"RemoveGuildAccessTagFromPlayer",
	"ModifyGuildAccessTagEditors",
	"RequestPublicAccessTags",
	"ChangeAccessTagPublicFlag",
	"UpdateGuildAccessTag",
	"SteamStartMicrotransaction",
	"SteamFinishMicrotransaction",
	"RequestXboxPurchaseIntent",
	"CloseXboxPurchaseIntent",
	"SteamIdHasActiveAccount",
	"CheckEmailAccountState",
	"LinkAccountToSteamId",
	"EpicIdHasActiveAccount",
	"LinkAccountToEpicId",
	"XboxIdHasActiveAccount",
	"InAppConfirmPaymentGooglePlay",
	"InAppConfirmPaymentAppleAppStore",
	"InAppPurchaseRequest",
	"InAppPurchaseFailed",
	"CharacterSubscriptionInfo",
	"AccountSubscriptionInfo",
	"BuyGvgSeasonBooster",
	"ChangeFlaggingPrepare",
	"OverCharge",
	"OverChargeEnd",
	"RequestTrusted",
	"ChangeGuildLogo",
	"PartyFinderRegisterForUpdates",
	"PartyFinderUnregisterForUpdates",
	"PartyFinderEnlistNewPartySearch",
	"PartyFinderDeletePartySearch",
	"PartyFinderChangePartySearch",
	"PartyFinderChangeRole",
	"PartyFinderApplyForGroup",
	"PartyFinderAcceptOrDeclineApplyForGroup",
	"PartyFinderGetEquipmentSnapshot",
	"PartyFinderRegisterApplicants",
	"PartyFinderUnregisterApplicants",
	"PartyFinderFulltextSearch",
	"PartyFinderRequestEquipmentSnapshot",
	"GetPersonalSeasonTrackerData",
	"GetPersonalSeasonPastRewardData",
	"UseConsumableFromInventory",
	"ClaimPersonalSeasonReward",
	"XignCodeMessageToServer",
	"BattlEyeMessageToServer",
	"SetNextTutorialState",
	"AddPlayerToMuteList",
	"RemovePlayerFromMuteList",
	"ProductShopUserEvent",
	"GetVanityUnlocks",
	"BuyVanityUnlocks",
	"GetMountSkins",
	"SetMountSkin",
	"SetWardrobe",
	"ChangeCustomization",
	"ChangePlayerIslandData",
	"GetGuildChallengePoints",
	"SmartQueueJoin",
	"SmartQueueLeave",
	"SmartQueueSelectSpawnCluster",
	"UpgradeHideout",
	"InitHideoutAttackStart",
	"InitHideoutAttackCancel",
	"HideoutFillNutrition",
	"HideoutGetInfo",
	"HideoutGetOwnerInfo",
	"HideoutSetTribute",
	"HideoutUpgradeWithPowerCrystal",
	"HideoutDeclareHQ",
	"HideoutUndeclareHQ",
	"HideoutGetHQRequirements",
	"HideoutBoost",
	"HideoutBoostConstruction",
	"OpenWorldAttackScheduleStart",
	"OpenWorldAttackScheduleCancel",
	"OpenWorldAttackConquerStart",
	"OpenWorldAttackConquerCancel",
	"GetOpenWorldAttackDetails",
	"GetNextOpenWorldAttackScheduleTime",
	"RecoverVaultFromHideout",
	"GetGuildEnergyDrainInfo",
	"ChannelingUpdate",
	"UseCorruptedShrine",
	"RequestEstimatedMarketValue",
	"LogFeedback",
	"GetInfamyInfo",
	"GetPartySmartClusterQueuePriority",
	"SetPartySmartClusterQueuePriority",
	"ClientAntiAutoClickerInfo",
	"ClientBotPatternDetectionInfo",
	"ClientAntiGatherClickerInfo",
	"LoadoutCreate",
	"LoadoutRead",
	"LoadoutReadHeaders",
	"LoadoutUpdate",
	"LoadoutDelete",
	"LoadoutOrderUpdate",
	"LoadoutEquip",
	"BatchUseItemCancel",
	"EnlistFactionWarfare",
	"GetFactionWarfareWeeklyReport",
	"ClaimFactionWarfareWeeklyReport",
	"GetFactionWarfareCampaignData",
	"ClaimFactionWarfareItemReward",
	"SendMemoryConsumption",
	"PickupCarriableObjectStart",
	"PickupCarriableObjectCancel",
	"SetSavingChestLogsFlag",
	"GetSavingChestLogsFlag",
	"RegisterGuestAccount",
	"ResendGuestAccountVerificationEmail",
	"DoSimpleActionStart",
	"DoSimpleActionCancel",
	"GetGvgSeasonContributionByActivity",
	"GetGvgSeasonContributionByCrystalLeague",
	"GetGuildMightCategoryContribution",
	"GetGuildMightCategoryOverview",
	"GetPvpChallengeData",
	"ClaimPvpChallengeWeeklyReward",
	"GetPersonalMightStats",
	"GetPvpChallengeSeasonRewards",
	"GetPvpChallengeSeasonRewardItems",
	"ClaimPvpChallengeSeasonRewards",
	"ClaimPvpChallengeSeasonRewardItems",
	"AuctionGetLoadoutOffers",
	"AuctionBuyLoadoutOffer",
	"AccountDeletionRequest",
	"AccountReactivationRequest",
	"CreateModeratorNotesForAccount",
	"GetModeratorNotesForAccount",
	"GetModerationEscalationDefiniton",
	"EventBasedPopupAddSeen",
	"GetItemKillHistory",
	"GetVanityConsumables",
	"EquipKillEmote",
	"ChangeKillEmotePlayOnKnockdownSetting",
	"BuyVanityConsumableCharges",
	"ReclaimVanityItem",
	"GetArenaRankings",
	"GetCrystalLeagueStatistics",
	"SendOptionsLog",
	"SendControlsOptionsLog",
	"MistsUseImmediateReturnExit",
	"MistsUseStaticEntrance",
	"MistsUseCityRoadsEntrance",
	"ChangeNewGuildMemberMail",
	"GetNewGuildMemberMail",
	"ChangeGuildFactionAllegiance",
	"GetGuildFactionAllegiance",
	"GuildBannerChange",
	"GuildGetOptionalStats",
	"GuildSetOptionalStats",
	"GetPlayerInfoForStalk",
	"PayGoldForCharacterTypeChange",
	"QuickSellAuctionQueryAction",
	"QuickSellAuctionSellAction",
	"FcmTokenToServer",
	"ApnsTokenToServer",
	"DeathRecap",
	"AuctionFetchFinishedAuctions",
	"AbortAuctionFetchFinishedAuctions",
	"RequestLegendaryEvenHistory",
	"PartyAnswerStartHuntRequest",
	"HuntAbort",
	"UseFindTrackSpellFromItemPrepare",
	"InteractWithTrackStart",
	"InteractWithTrackCancel",
	"TerritoryRaidStart",
	"TerritoryRaidCancel",
	"TerritoryClaimRaidedRawEnergyCrystalResult",
	"GvGSeasonPlayerGuildParticipationDetails",
	"DailyMightBonus",
	"ClaimDailyMightBonus",
	"GetFortificationGroupInfo",
	"UpgradeFortificationGroup",
	"CancelUpgradeFortificationGroup",
	"DowngradeFortificationGroup",
	"GetClusterActivityChestEstimates",
	"PartyReadyCheckBegin",
	"PartyReadyCheckUpdate",
	"ClaimAlbionJournalReward",
	"TrackAlbionJournalAchievements",
	"TrackAlbionJournalAchievementSubCategory",
	"RequestOutlandsTeleportationUsage",
	"PickupFromPiledObjectStart",
	"PickupFromPiledObjectCancel",
	"AssetOverview",
	"AssetOverviewTabs",
	"AssetOverviewTabContent",
	"AssetOverviewUnfreezeCache",
	"AssetOverviewSearch",
	"AssetOverviewSearchTabs",
	"AssetOverviewSearchTabContent",
	"AssetOverviewRecoverPlayerVault",
	"ImmortalizeKillTrophy",
	"ArmorySearch",
	"ArmoryItemUsageStatistics",
	"ArmoryActivityUsageStatistics",
	"HellDungeonUseStaticEntrance",
	"TravelIslandShowroom",
	"GetXuids",
	"XboxServiceTicket",
	"EvaluatePlatformPerks",
	"LinkAccountToXbox",
	"TravelFactionWarfarePortal",
	"RequestRedZoneEventStandings",
	"GetZergDebuffInfo",
	"RequestLoreSnippetStates",
	"RetrieveCarriableObjectStart",
	"RetrieveCarriableObjectCancel",
}
